"""Initial migration

Revision ID: ad8624fd66d5
Revises: 
Create Date: 2024-03-06 14:47:43.970580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad8624fd66d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musica',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('duracao_ms', sa.Integer(), nullable=False),
    sa.Column('artistas', sa.String(length=255), nullable=False),
    sa.Column('nome_album', sa.String(length=255), nullable=True),
    sa.Column('data_lancamento', sa.Date(), nullable=False),
    sa.Column('total_musicas_album', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('musica')
    # ### end Alembic commands ###
